<a href="https://colab.research.google.com/github/gksrbans/-NLP-/blob/main/ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 정리

In [ ]:
import numpy as np

In [ ]:
list1 = [1, 2, 3]
#print(list1)

array1 = np.array(list1)
print(array1)
print(type(array1))


[1 2 3]
<class 'numpy.ndarray'>


ndarray의 형태와 차원

In [ ]:
array1 = np.array([1,2,3])
array2= np.array([[1,2,3],[2,3,4]])
array3 = np.array([[1,2,3]])

print(array1.shape)
print(array2.shape)
print(array3.shape)

print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

(3,)
(2, 3)
(1, 3)
1
2
2


In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
# int형이 아닌 float형 또는 문자가 올경우 그것에 따라감

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
# 형변환 astype()
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [ ]:
array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]
